version: "3"
services:
  mitodo:
    container_name: mitodo
    restart: always
    build: ./
    volumes:
      - ./:/var/www/mitodo
    links:
      - mongo
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - PORT=5000

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - mongodb+srv://todo:1234@atlascluster.kd45zly.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
